### ISSUE TITLE
Atualizar o changelog até a versão 0.1.2

### ISSUE THREAD

**Issue by augusto-herrmann** [gestaogovbr/Ro-dou#103]
O registro de mudanças de versão vai só até a versão 0.1.0, mas a última tag é 0.1.2. Documentar as alterações feitas nas versões 0.1.1 e 0.1.2.

**Comment by edulauer** [comment]
Alterações documentadas no commit https://github.com/gestaogovbr/Ro-dou/commit/f2db1c51c8b1795e7a62bbc4236e171da5f18c12
