### ISSUE TITLE
Documentar completamente a especificação do arquivo yaml

### ISSUE THREAD

**Issue by augusto-herrmann** [gestaogovbr/Ro-dou#11]
A documentação já contém exemplos, porém seria importante conter a documentação completa de todas as opções que estão disponíveis para cada parâmetro do arquivo yaml, quais são os valores possíveis e os seus efeitos.

**Comment by edulauer** [comment]
Disponível na nova página de documentação do Ro-DOU (https://gestaogovbr.github.io/Ro-dou/)
