### ISSUE TITLE
Remover `schemas/ro-dou.json`

### ISSUE THREAD

**Issue by augusto-herrmann** [gestaogovbr/Ro-dou#152]
Com a implementação de #73, parece não ser mais necessário manter o arquivo `schemas/ro-dou.json`.

Proponho remover a pasta `schemas`. Em vez disso, temos essas definições no Pydantic em [`src/schemas.py`](https://github.com/gestaogovbr/Ro-dou/blob/63b34b27b5d643aa86eccf370c64a321590d527c/src/schemas.py).

Com isso, fecharíamos também:
- #68 
- #70

De acordo, @edulauer e @vitorbellini ?

**Comment by edulauer** [comment]
@augusto-herrmann de acordo!
