### ISSUE TITLE
Identificar publicação de Edição Extra

### ISSUE THREAD

**Issue by edulauer** [gestaogovbr/Ro-dou#16]
Verificar possibilidade de checar se houve publicação de edições extras antes de fazer a pesquisa de termos pelo Ro-dou nestas edições.

Exemplo:
Na página https://www.in.gov.br/leiturajornal quando há edição extra é exibido o elemento"Edição Extra" em laranja. O Ro-dou poderia utilizar essa checagem antes de executar a task exec_dou_search.

**Comment by nitaibezerra** [comment]
Fala Lauer. Blz?

Como essa informação poderia melhorar a execução do Ro-dou? Essa proposta resolve um bug ou adiciona uma nova funcionalidade?

**Comment by edulauer** [comment]
Nitai, blz?

Essa nova feature é uma sugestão do @washolive. Praticamente falando, hoje temos uma DAG que roda no final do dia que faz uma varredura de movimentação de servidores nas edições extras. Aí a ideia seria de, antes de rodar a task de varredura, ter alguma checagem anterior para verificar se teve ou não publicação de edição extra no dia, evitando assim processamentos desnecessários.

**Comment by edulauer** [comment]
Nitai, entendi. 

Quanto ao custo de processamento eu me refiro mais a execução da DAG do Airflow de ter q executar diariamente a busca de cada termo (nome de servidor) na API da IN (cerca de 2500 servidores), um a um, independente se teve ou não publicação de Edicão Extra no dia. Mas concordo que demandaria muito esforço de implementação no código do Ro-Dou para algo muito específico. Pensando melhor, talvez poderíamos criar outra DAG independente do Ro-Dou para fazer esse tipo de validação, a ser executada antes da nossa DAG do Ro-Dou de Edição Extra.

Vou conversar com o @washolive a respeito, mas creio que podemos fechar esta issue. 

Obrigado Nitai pela atenção! Abraços!

**Comment by nitaibezerra** [comment]
Realmente, Lauer. Eu não tinha lembrado que existe o loop que percorre cada um dos 2500 termos a serem pesquisados. De toda forma essa evolução é uma questão de prioridades. Se esse processamento realmente está ocasionando um consumo bem maior de processamento, o que acredito que não, eu ainda manteria as coisas como estão. É o tradeoff entre otimizar o tempo de execução e, de outro lado, ter mais um código para manter. :)

**Comment by edulauer** [comment]
Com a opção de search via INLABS, essa issue faz-se desnecessária para consulta de vários dados em um banco de dados.
