### ISSUE TITLE
Erro na instalacao

### ISSUE THREAD

**Issue by rcalixto** [gestaogovbr/Ro-dou#59]
executor failed running [/bin/bash -o pipefail -o errexit -o nounset -o nolog -c pip install --no-cache-dir --user     apache-airflow[microsoft.mssql,google_auth]     apache-airflow-providers-fastetl]: exit code: 1
ERROR: Service 'airflow-webserver' failed to build : Build failed
make: *** [setup-containers] Error 1

**Comment by vitorbellini** [comment]
@rcalixto foram feitos commits recentemente. Esse erro parece não ocorrer mais. Testa de novo e dá um retorno aí se funcionar ou não.

**Comment by rflfnds** [comment]
Boa tarde,

Clonei o projeto hoje e ao executar esta apresentando este erro:

failed to solve: process "/bin/bash -o pipefail -o errexit -o nounset -o nolog -c pip install --no-cache-dir --user 'apache-airflow[microsoft.mssql,google_auth]'" did not complete successfully: exit code: 1
make: *** [setup-containers] Error 17

Conforme sugerido no comentário acima, não possível: permissão negada:

➜ docker pull ghcr.io/economiagovbr/ro-dou:latest
Error response from daemon: Head "https://ghcr.io/v2/economiagovbr/ro-dou/manifests/latest": denied

**Comment by edulauer** [comment]
Conforme testes realizados, o link da imagem do ro-dou está ativo.
