### ISSUE TITLE
Erro em rodar postgres

### ISSUE THREAD

**Issue by nickbuttner** [gestaogovbr/Ro-dou#61]
Estou tendo problemas para rodar o Ro-dou. 
Ao dar "make run", os containers são criados ou startados mas o de postgres retorna erro e mensagem de que a dependência não está saudável. Já apaguei tudo, refiz.
Instalei o Docker, inicio o Docker antes....

O que pode ser?
Como posso resolver?

Obrigado.

**Comment by edulauer** [comment]
@nickbuttner, é possível enviar maiores detalhes do erro, para averiguarmos?

- Já tentou remover as imagens e volumes criadas no seu ambiente (docker images e docker rmi) e criá-las novamente?
- Verifique se as permissões da pasta mnt/pgdata estão a mesma do usuário do docker e não root.

**Comment by edulauer** [comment]
@nickbuttner, pelo log parece que seu docker não está conseguindo se conectar com os servidores externos para criar a imagem do serviço do Airflow local, que é necessário para rodar o Ro-Dou. Se puder dá uma verificada nas suas configurações de rede e DNS junto com o Docker.

As instruções deste repositório indicam para gerar localmente as imagens do Docker a partir do arquivo Dockerfile. Você pode tentar utilizar as imagens dos serviços já existentes no repositório do gestaogovbr. Se puder também fazer a seguinte alteração e testar:

Arquivo docker-compose.yml
Substituir as linhas 42 e 43:
`      build:`
`        context: .`
por:
`      image: ghcr.io/gestaogovbr/airflow2-docker:latest`

Em seguida, testar com o comando _make run_

**Comment by nickbuttner** [comment]
@edulauer Tu está certo. É alguma configuração aqui. Usei a imagem e funciona.

Como posso resolver a questão de rede para poder rodar na minha máquina?
