### ISSUE TITLE
Filtar resultados do DOU por órgão

### ISSUE THREAD

**Issue by edulauer** [gestaogovbr/Ro-dou#67]
Em muitos casos o usuário poderia apenas desejar as publicações de determinado órgão no DOU. A ideia seria criar um parâmetro adicional no YAML de órgão. Embora não seja um parâmetro disponível na consulta da IN, poderia ser filtrado no clipping apenas as publicações da lista de órgãos desejados.

**Comment by washolive** [comment]
Recebemos uma solicitação dessa filtro recentemente. 
Existe um campo na pesquisa do DOU para selecionar um órgão. A URL gerada fica no seguinte formato, exemplo:
https://www.in.gov.br/consulta/-/buscar/dou?q=nomear&s=do2&exactDate=dia&sortType=0&delta=20&orgPrin=Minist%C3%A9rio+da+Gest%C3%A3o+e+da+Inova%C3%A7%C3%A3o+em+Servi%C3%A7os+P%C3%BAblicos
