### ISSUE TITLE
Aplicar teste `tests/test_validate_yaml_schemas.py` no repo `cdata/airflow-dags/dags/ro_dou/dag_confs`

### ISSUE THREAD

**Issue by vitorbellini** [gestaogovbr/Ro-dou#72]
Aplicar teste [tests/test_validate_yaml_schemas.py](https://github.com/gestaogovbr/Ro-dou/blob/validate-yaml/tests/test_validate_yaml_schemas.py) no repo [cdata/airflow-dags//dags/ro_dou/dag_confs](https://git.economia.gov.br/seges-cginf/airflow-dags/-/tree/master/dags%2Fro_dou%2Fdag_confs)

**Comment by augusto-herrmann** [comment]
Este é o repositório público do Ro-DOU. Sugiro discutirmos e implementarmos em âmbito interno a forma como aplicamos ele em nossos processos internos.
