### ISSUE TITLE
Resultados errados da pesquisa

### ISSUE THREAD

**Issue by nickbuttner** [gestaogovbr/Ro-dou#76]
Buscando por termos como **IRPJ** e **CSLL**, não retornaram no dia seguinte resultado do dia 19/12 referente à "Solução de Consulta 306/2023", que possui "IRPJ" e "CSLL".

A pesquisa não retorna resultados exatos. Mesmo passando **is_exact_search** e **force_rematch** como **true**.

Preciso de termos como **e-CAC**, **E-Social** e **@RFB**. Mesmo alterando o método **_normalize**, não tenho o retorno exato. A busca ignora os especiais.

Preciso de resultados exatos mas não estou conseguindo. Fiz alterações no método **_really_matched**, mas sem sucesso. Poderias me dar um help, por favor?

**Comment by augusto-herrmann** [comment]
Olá, @nickbuttner.

Você chegou a pesquisar manualmente no Diário Oficial da União para verificar se realmente existe uma publicação com o termo utilizado naquela data, na seção informada? São 3 seções no D.O.U. e em alguns dias existem também edições extras. O Ro-DOU funciona em cima da própria pesquisa do D.O.U., por isso, para poder depurar qualquer possível divergência nos resultados, é necessário reproduzir uma pesquisa (link do resultado de pesquisa na Imprensa Nacional).

Exemplo: [pesquisa por "IRPJ" no dia 19/12/2023](https://www.in.gov.br/consulta/-/buscar/dou?q=+IPRJ&s=todos&exactDate=personalizado&sortType=0&publishFrom=19-12-2023&publishTo=19-12-2023), não retorna nenhum resultado. Logo, é esperado que o Ro-DOU também não irá retornar nenhum resultado.

**Comment by edulauer** [comment]
@nickbuttner Realizei os testes no Ro-DOU com os termos **IRPJ, CSLL** para o dia 19/12 e retornou um resultado para cada conforme a pesquisa da IN. Fiz um teste também para E-CAC para o dia 21/02/24 e o mesmo retornou vários resultados correspondentes. Pode anexar o YAML de configuração que você está utilizando?

**Comment by edulauer** [comment]
@nickbuttner dag:
```
  id: basic_example
  description: DAG de teste
  search:
    terms:
    - IRPJ
    - CSLL
  report:
    emails:
      - destination@economia.gov.br
    subject: "Teste do Ro-dou"
```
